### ISSUE TITLE
32-bit platforms

### ISSUE THREAD

**Issue by mbutterweckINNTEC** [rigtorp/ipc-bench#23]
On 32 bit ARM delta calculation shall be as this:
```
    delta = ((stop.tv_sec - start.tv_sec) * 1000000000LL +
             (stop.tv_nsec - start.tv_nsec));
```
and
```
    delta = (stop.tv_sec - start.tv_sec) * 1000000000LL +
            (stop.tv_usec - start.tv_usec) * 1000LL;
```
Otherwise the expression overflows, because `long` is 4 byte in size and by default literals are `int`.
It was like a time travel, negative latency :smiley:

**Comment by rigtorp** [comment]
Thanks for reporting!
